# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow, coders):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(788, 677)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(630, 160, 121, 41))
        self.pushButton.setObjectName("pushButton")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(360, 30, 391, 110))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBox.setValue(0.1)
        self.doubleSpinBox.setMaximum(1.0)
        self.doubleSpinBox.setSingleStep(0.01)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout_2.addWidget(self.doubleSpinBox, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox.setMaximum(1000000)
        self.spinBox.setObjectName("spinBox")
        self.spinBox.setValue(1000)
        self.gridLayout_2.addWidget(self.spinBox, 2, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.single = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.single.setObjectName("single")
        self.verticalLayout.addWidget(self.single)
        self.group = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.group.setObjectName("group")
        self.verticalLayout.addWidget(self.group)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 20, 111, 31))
        self.label_4.setObjectName("label_4")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(100, 30, 191, 590))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")

        self.checkBoxList = []
        self.coders = coders
        i = 1
        for coder in coders:
            checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
            checkBox.setObjectName(f"checkBox_{i}")
            self.verticalLayout_3.addWidget(checkBox)
            i += 1
            self.checkBoxList.append(checkBox)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 788, 26))
        self.menubar.setObjectName("menubar")
        self.menuParametry = QtWidgets.QMenu(self.menubar)
        self.menuParametry.setObjectName("menuParametry")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuParametry.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "NiDUC"))
        self.pushButton.setText(_translate("MainWindow", "Uruchom"))
        self.label_3.setText(_translate("MainWindow", "Liczba bitów przesyłanej wiadomości: "))
        self.label_2.setText(_translate("MainWindow", "Prawdopodobieństwo przekłamania: "))
        self.single.setText(_translate("MainWindow", "Błedy pojedyncze"))
        self.single.setChecked(True)

        self.group.setText(_translate("MainWindow", "Błedy grupowe"))
        self.label.setText(_translate("MainWindow", "Typ kanału transmisyjnego:"))
        self.label_4.setText(_translate("MainWindow", "Kodowania:"))
        self.menuParametry.setTitle(_translate("MainWindow", "Parametry"))

        i = 0
        for checkBox in self.checkBoxList:
            checkBox.setText(_translate("MainWindow", str(self.coders[i])))
            i += 1
